<a href="https://colab.research.google.com/github/saihaneesh26/hackerearth_challenges/blob/main/hackerearth_predict_the_power.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#highest accuracy is obtained using RandomForestClassifier - 95.01% - n_estimators=100
#DecisionTree - 93%
#SVM -  60%
#other  approx 30-50%
#Rank in contest - 195
import random
import tensorflow as tf
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA

In [ ]:
main_db = pd.read_csv('/content/train.csv')
main_db

tracking_id  ... windmill_generated_power(kW/h)
0        WM_33725  ...                       6.766521
1          WM_698  ...                       5.966275
2        WM_39146  ...                       2.874342
3         WM_6757  ...                      14.851089
4        WM_21521  ...                       3.519074
...           ...  ...                            ...
28195     WM_7814  ...                       9.587934
28196    WM_32512  ...                       4.522195
28197     WM_5193  ...                      11.096599
28198    WM_12173  ...                       9.373239
28199    WM_33004  ...                       2.860342

[28200 rows x 22 columns]

In [ ]:
main_db.columns

main_db['cloud_level'].count()

27924

In [ ]:
main_db = main_db.dropna(subset=["tracking_id","datetime"])

In [ ]:
main_db1 = main_db.fillna(main_db.mean())

In [ ]:
mode1 = main_db["cloud_level"].value_counts()
print(mode1)
#mode2=main_db["turbine_status"].value_counts()

def mod1():
  x = random.randint(0,9)
  if(x%2==0):
    return 'Low'
  else:
    return 'Medium'
main_db1["cloud_level"].fillna(mod1(),inplace=True)
main_db1["turbine_status"].fillna("BB",inplace=True)
mode1 = main_db["cloud_level"].value_counts()
print(mode1)

Low              13921
Medium           13704
Extremely Low      299
Name: cloud_level, dtype: int64
Low              13921
Medium           13704
Extremely Low      299
Name: cloud_level, dtype: int64


In [ ]:
db1 = pd.get_dummies(main_db1,columns = ["cloud_level","turbine_status"])
tid=np.array(db1["tracking_id"])
dt = np.array(db1["datetime"])
Y_DB = np.array(db1["windmill_generated_power(kW/h)"])
Y_DB = Y_DB.reshape(-1,1)
s = StandardScaler()
s.fit_transform(Y_DB)

array([[ 0.23664324],
       [-0.06111673],
       [-1.2115804 ],
       ...,
       [ 1.84780309],
       [ 1.20656568],
       [-1.21678959]])

In [ ]:
db2 = db1.drop(columns=['tracking_id',"datetime"])
print(str(db2.isnull().sum()))

wind_speed(m/s)                   0
atmospheric_temperature(°C)       0
shaft_temperature(°C)             0
blades_angle(°)                   0
gearbox_temperature(°C)           0
engine_temperature(°C)            0
motor_torque(N-m)                 0
generator_temperature(°C)         0
atmospheric_pressure(Pascal)      0
area_temperature(°C)              0
windmill_body_temperature(°C)     0
wind_direction(°)                 0
resistance(ohm)                   0
rotor_torque(N-m)                 0
blade_length(m)                   0
blade_breadth(m)                  0
windmill_height(m)                0
windmill_generated_power(kW/h)    0
cloud_level_Extremely Low         0
cloud_level_Low                   0
cloud_level_Medium                0
turbine_status_A                  0
turbine_status_A2                 0
turbine_status_AAA                0
turbine_status_AB                 0
turbine_status_ABC                0
turbine_status_AC                 0
turbine_status_B            

In [ ]:
# minval=db2.min()
# maxval = db2.max()

# db2 -=db2.min()
# db2 /=db2.max()

scaler = StandardScaler()

scaled_features =  scaler.fit_transform(db2.values)
db2 =pd.DataFrame(scaled_features,index = db2.index,columns=db2.columns)
db2

wind_speed(m/s)  ...  turbine_status_D
0             0.339678  ...         -0.270446
1             2.276497  ...         -0.270446
2             0.348435  ...         -0.270446
3             2.236798  ...         -0.270446
4            -0.768260  ...         -0.270446
...                ...  ...               ...
28195         0.338962  ...         -0.270446
28196         0.331466  ...         -0.270446
28197         0.330988  ...          3.697596
28198         0.347719  ...         -0.270446
28199        -0.335670  ...         -0.270446

[28200 rows x 35 columns]

In [ ]:
db2["tracking_id"]=tid
db2["datetime"]=dt
print(str(db2.isnull().sum()))

wind_speed(m/s)                   0
atmospheric_temperature(°C)       0
shaft_temperature(°C)             0
blades_angle(°)                   0
gearbox_temperature(°C)           0
engine_temperature(°C)            0
motor_torque(N-m)                 0
generator_temperature(°C)         0
atmospheric_pressure(Pascal)      0
area_temperature(°C)              0
windmill_body_temperature(°C)     0
wind_direction(°)                 0
resistance(ohm)                   0
rotor_torque(N-m)                 0
blade_length(m)                   0
blade_breadth(m)                  0
windmill_height(m)                0
windmill_generated_power(kW/h)    0
cloud_level_Extremely Low         0
cloud_level_Low                   0
cloud_level_Medium                0
turbine_status_A                  0
turbine_status_A2                 0
turbine_status_AAA                0
turbine_status_AB                 0
turbine_status_ABC                0
turbine_status_AC                 0
turbine_status_B            

In [ ]:
Y = pd.DataFrame(db2["windmill_generated_power(kW/h)"])
X = db2.drop(["windmill_generated_power(kW/h)","tracking_id","datetime"],axis=1)
X = X.drop(columns=['wind_direction(°)','blade_length(m)','atmospheric_pressure(Pascal)','atmospheric_temperature(°C)','windmill_body_temperature(°C)'])

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(X,Y)
X

wind_speed(m/s)  ...  turbine_status_D
0             0.339678  ...         -0.270446
1             2.276497  ...         -0.270446
2             0.348435  ...         -0.270446
3             2.236798  ...         -0.270446
4            -0.768260  ...         -0.270446
...                ...  ...               ...
28195         0.338962  ...         -0.270446
28196         0.331466  ...         -0.270446
28197         0.330988  ...          3.697596
28198         0.347719  ...         -0.270446
28199        -0.335670  ...         -0.270446

[28200 rows x 29 columns]

In [ ]:
print(x_train.shape)
print(x_test.shape)

(21150, 29)
(7050, 29)


In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(criterion='mse')
regressor.fit(X,Y)  

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [ ]:
regressor.score(x_test,y_test)

0.9930643249162504

In [ ]:
testdb = pd.read_csv('/content/test.csv')
#main_db = main_db.dropna(subset=["tracking_id","datetime"])
testdb

tracking_id             datetime  ...  blade_breadth(m)  windmill_height(m)
0        WM_19817  2019-04-17 08:53:20  ...          0.403965           25.572431
1        WM_18723  2019-03-30 07:43:20  ...          0.444755           24.371823
2        WM_34552  2019-08-10 11:33:20  ...          0.387368           27.654677
3        WM_28570  2019-06-26 03:53:20  ...          0.450478           24.189426
4        WM_36934  2019-08-27 16:43:20  ...          0.368355            4.885440
...           ...                  ...  ...               ...                 ...
12081    WM_13376  2019-02-12 11:33:20  ...          0.407771           20.888674
12082     WM_1630  2018-11-12 17:33:20  ...          0.367823           24.793606
12083    WM_24703  2019-05-27 11:53:20  ...          0.459887            5.653451
12084    WM_22893  2019-05-13 21:53:20  ...          0.394680           24.591364
12085    WM_14513  2019-02-20 23:43:20  ...          0.490893           21.665001

[12086 rows x 21 columns]

In [ ]:
#testdb = testdb.dropna(subset=["tracking_id","datetime"])
testdb = testdb.drop(columns=['wind_direction(°)','blade_length(m)','atmospheric_pressure(Pascal)','atmospheric_temperature(°C)','windmill_body_temperature(°C)'])

In [ ]:
print(str(testdb.isnull().sum()))

tracking_id                    0
datetime                       0
wind_speed(m/s)              126
shaft_temperature(°C)          1
blades_angle(°)              106
gearbox_temperature(°C)        1
engine_temperature(°C)         5
motor_torque(N-m)             11
generator_temperature(°C)      5
area_temperature(°C)           1
resistance(ohm)                0
rotor_torque(N-m)            281
turbine_status               797
cloud_level                  125
blade_breadth(m)               0
windmill_height(m)           255
dtype: int64


In [ ]:
print(testdb["cloud_level"].mode())
print(testdb["turbine_status"].mode())
testdb["cloud_level"].fillna("Low",inplace=True)
testdb["turbine_status"].fillna("BB",inplace=True)
testdb = testdb.fillna(testdb.mean())

0    Low
dtype: object
0    BB
dtype: object


In [ ]:
l = []
tid=np.array(testdb["tracking_id"])
dt = np.array(testdb["datetime"])
ndb = testdb.drop(columns=["tracking_id",'datetime'])
ndb1 = pd.get_dummies(ndb,columns = ["cloud_level","turbine_status"])
ndb1 = scaler.fit_transform(ndb1)
#ndb1 = pca.fit_transform(ndb1)

In [ ]:
regressor.predict(ndb1)

array([-1.27289499, -1.36497758, -1.05892246, ..., -0.32912495,
       -0.2819942 ,  1.48975663])

In [ ]:
finaldb = pd.DataFrame()
finaldb["tracking_id"]=tid
finaldb["datetime"]=dt

finaldb["windmill_generated_power(kW/h)"]=regressor.predict(ndb1)
finaldb

tracking_id             datetime  windmill_generated_power(kW/h)
0        WM_19817  2019-04-17 08:53:20                       -1.272895
1        WM_18723  2019-03-30 07:43:20                       -1.364978
2        WM_34552  2019-08-10 11:33:20                       -1.058922
3        WM_28570  2019-06-26 03:53:20                        0.291434
4        WM_36934  2019-08-27 16:43:20                       -0.972680
...           ...                  ...                             ...
12081    WM_13376  2019-02-12 11:33:20                        0.131006
12082     WM_1630  2018-11-12 17:33:20                       -1.158529
12083    WM_24703  2019-05-27 11:53:20                       -0.329125
12084    WM_22893  2019-05-13 21:53:20                       -0.281994
12085    WM_14513  2019-02-20 23:43:20                        1.489757

[12086 rows x 3 columns]

In [ ]:
#finaldb["windmill_generated_power(kW/h)"] = finaldb["windmill_generated_power(kW/h)"]
l = pd.DataFrame(finaldb)
l_data1 = s.inverse_transform(finaldb["windmill_generated_power(kW/h)"])
l_data1
finaldb["windmill_generated_power(kW/h)"]=np.array(l_data1)
finaldb

tracking_id             datetime  windmill_generated_power(kW/h)
0        WM_19817  2019-04-17 08:53:20                        2.709556
1        WM_18723  2019-03-30 07:43:20                        2.462079
2        WM_34552  2019-08-10 11:33:20                        3.284618
3        WM_28570  2019-06-26 03:53:20                        6.913772
4        WM_36934  2019-08-27 16:43:20                        3.516401
...           ...                  ...                             ...
12081    WM_13376  2019-02-12 11:33:20                        6.482616
12082     WM_1630  2018-11-12 17:33:20                        3.016920
12083    WM_24703  2019-05-27 11:53:20                        5.245988
12084    WM_22893  2019-05-13 21:53:20                        5.372655
12085    WM_14513  2019-02-20 23:43:20                       10.134330

[12086 rows x 3 columns]

In [ ]:
finaldb.to_csv("s3.csv")

In [ ]:
from sklearn.tree import DecisionTreeRegressor
clf = DecisionTreeRegressor(random_state=1,criterion='mae') 

In [ ]:
clf.fit(X.astype("float"),Y.astype("float"))

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mae', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=1, splitter='best')

In [ ]:
clf.score(x_train.astype("float"),y_train.astype("float"))

1.0

In [ ]:
l = clf.predict(ndb1)
l

array([-1.49725444, -1.46237783, -0.96688159, ..., -0.16359839,
       -0.19939791,  1.64292533])

In [ ]:
finaldb_dt = pd.DataFrame()

In [ ]:

finaldb_dt["tracking_id"]=tid
finaldb_dt["datetime"]=dt

finaldb_dt["windmill_generated_power(kW/h)"]=l
finaldb_dt

tracking_id             datetime  windmill_generated_power(kW/h)
0        WM_19817  2019-04-17 08:53:20                       -1.497254
1        WM_18723  2019-03-30 07:43:20                       -1.462378
2        WM_34552  2019-08-10 11:33:20                       -0.966882
3        WM_28570  2019-06-26 03:53:20                        0.282476
4        WM_36934  2019-08-27 16:43:20                       -1.112160
...           ...                  ...                             ...
12081    WM_13376  2019-02-12 11:33:20                        0.091013
12082     WM_1630  2018-11-12 17:33:20                       -1.201360
12083    WM_24703  2019-05-27 11:53:20                       -0.163598
12084    WM_22893  2019-05-13 21:53:20                       -0.199398
12085    WM_14513  2019-02-20 23:43:20                        1.642925

[12086 rows x 3 columns]

In [ ]:
dt = pd.DataFrame(finaldb_dt)
l_data = s.inverse_transform(finaldb_dt["windmill_generated_power(kW/h)"])
l_data


array([ 2.10657766,  2.20031042,  3.53198315, ...,  5.69084985,
        5.59463672, 10.54597925])

In [ ]:
l_data1

array([ 2.70955573,  2.46207882,  3.28461838, ...,  5.24598834,
        5.37265475, 10.13433015])

In [ ]:
l_data/2+l_data1/2

array([ 2.4080667 ,  2.33119462,  3.40830077, ...,  5.46841909,
        5.48364573, 10.3401547 ])

In [ ]:
finaldb_dt["windmill_generated_power(kW/h)"]=np.array((l_data1/2+l_data/2))
finaldb_dt

tracking_id             datetime  windmill_generated_power(kW/h)
0        WM_19817  2019-04-17 08:53:20                        2.408067
1        WM_18723  2019-03-30 07:43:20                        2.331195
2        WM_34552  2019-08-10 11:33:20                        3.408301
3        WM_28570  2019-06-26 03:53:20                        6.901736
4        WM_36934  2019-08-27 16:43:20                        3.328970
...           ...                  ...                             ...
12081    WM_13376  2019-02-12 11:33:20                        6.428873
12082     WM_1630  2018-11-12 17:33:20                        2.959365
12083    WM_24703  2019-05-27 11:53:20                        5.468419
12084    WM_22893  2019-05-13 21:53:20                        5.483646
12085    WM_14513  2019-02-20 23:43:20                       10.340155

[12086 rows x 3 columns]

In [ ]:
finaldb_dt.to_csv("avag.csv")

In [ ]:
#SVM
from sklearn import svm

In [ ]:
svmclf = svm.SVR(kernel='rbf',C=10,degree=6)
svmclf.fit(x_train,y_train)
svmclf.score(x_test,y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.5941627544201898

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
model_kn = KNeighborsRegressor()
model_kn.fit(x_train,y_train)
model_kn.score(x_test,y_test)

0.32121638795984

In [ ]:
from sklearn.linear_model import LassoCV
model_lv = LassoCV()
model_lv.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:1088: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LassoCV(alphas=None, copy_X=True, cv=None, eps=0.001, fit_intercept=True,
        max_iter=1000, n_alphas=100, n_jobs=None, normalize=False,
        positive=False, precompute='auto', random_state=None,
        selection='cyclic', tol=0.0001, verbose=False)

In [ ]:
model_lv.score(x_test,y_test)

0.3735789344674451

In [ ]:
from sklearn.linear_model import RidgeCV
model_r = RidgeCV()
model_r.fit(x_train, y_train)

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), cv=None, fit_intercept=True,
        gcv_mode=None, normalize=False, scoring=None, store_cv_values=False)

In [ ]:
model_r.score(x_test,y_test)

0.37162346692721615

In [ ]:
from sklearn.linear_model import ElasticNetCV
model_ev = ElasticNetCV()
model_ev.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:1088: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


ElasticNetCV(alphas=None, copy_X=True, cv=None, eps=0.001, fit_intercept=True,
             l1_ratio=0.5, max_iter=1000, n_alphas=100, n_jobs=None,
             normalize=False, positive=False, precompute='auto',
             random_state=None, selection='cyclic', tol=0.0001, verbose=0)

In [ ]:
model_ev.score(x_test,y_test)

0.37222362707207796

In [ ]:
from sklearn.naive_bayes import GaussianNB
model_gnb = GaussianNB()
model_gnb.fit(x_train.astype("int"),y_train.astype("int"))
model_gnb.score(x_test.astype("int"),y_test.astype("int"))

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.26745718050065875

In [ ]:
model = tf.keras.Sequential([
                                    tf.keras.layers.Dense(1028,input_shape=(29,)),
                                    tf.keras.layers.Dense(512,activation='relu'),
                                    tf.keras.layers.Dense(256,activation='relu'),
                                    tf.keras.layers.Dense(128,activation='relu'),
                                    tf.keras.layers.Dense(64,activation='relu'),
                                    tf.keras.layers.Dense(1,activation='sigmoid')
])

In [ ]:
model.compile(optimizer='adam',loss='mse',metrics=['accuracy'])

In [ ]:
model.fit(X.astype('float'),Y,epochs=4)

Epoch 1/4
882/882 [==============================] - 2s 3ms/step - loss: 0.6628 - accuracy: 0.0000e+00
Epoch 2/4
882/882 [==============================] - 2s 3ms/step - loss: 0.6621 - accuracy: 0.0000e+00
Epoch 3/4
882/882 [==============================] - 2s 3ms/step - loss: 0.6624 - accuracy: 0.0000e+00
Epoch 4/4
882/882 [==============================] - 2s 3ms/step - loss: 0.6613 - accuracy: 0.0000e+00
