<a href="https://colab.research.google.com/github/saihaneesh26/hackerearth_challenges/blob/main/predict_churn_risk_score.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [ ]:
df=pd.read_csv('/content/train.csv')
df=df.dropna()

In [ ]:
df.churn_risk_score.unique()

array([ 2,  5,  3,  4, -1,  1])

In [ ]:
df=df.dropna(subset=['churn_risk_score'])

In [ ]:
Y=pd.DataFrame(df['churn_risk_score'])
Y

churn_risk_score
0                     2
2                     5
3                     5
4                     5
5                     3
...                 ...
36985                 2
36986                 3
36988                 5
36990                 3
36991                 2

[28373 rows x 1 columns]

In [ ]:
def s(x):
  if x==-1:
    return int(6)
  return int(x)
Y.churn_risk_score=Y.churn_risk_score.apply(s)
#print(type(Y.churn_risk_score[0]))

In [ ]:
Y.churn_risk_score.unique() # -1 -> 0

array([2, 5, 3, 4, 6, 1])

In [ ]:
X=df.copy()
X=X.drop(['Name','customer_id','security_no','joining_date','referral_id','last_visit_time','churn_risk_score'],axis=1)
X.head()

age gender  ...     complaint_status                  feedback
0   18      F  ...       Not Applicable  Products always in Stock
2   44      F  ...  Solved in Follow-up              Poor Website
3   37      M  ...             Unsolved              Poor Website
4   31      F  ...               Solved              Poor Website
5   13      M  ...             Unsolved       No reason specified

[5 rows x 18 columns]

In [ ]:
scaler=StandardScaler()
X=pd.get_dummies(X,columns=['gender','region_category','membership_category','joined_through_referral','preferred_offer_types','medium_of_operation','internet_option','used_special_discount','offer_application_preference','past_complaint','complaint_status','feedback'])
#X=pd.get_dummies(df['gender'])
X.columns

Index(['age', 'days_since_last_login', 'avg_time_spent',
       'avg_transaction_value', 'avg_frequency_login_days', 'points_in_wallet',
       'gender_F', 'gender_M', 'gender_Unknown', 'region_category_City',
       'region_category_Town', 'region_category_Village',
       'membership_category_Basic Membership',
       'membership_category_Gold Membership',
       'membership_category_No Membership',
       'membership_category_Platinum Membership',
       'membership_category_Premium Membership',
       'membership_category_Silver Membership', 'joined_through_referral_?',
       'joined_through_referral_No', 'joined_through_referral_Yes',
       'preferred_offer_types_Credit/Debit Card Offers',
       'preferred_offer_types_Gift Vouchers/Coupons',
       'preferred_offer_types_Without Offers', 'medium_of_operation_?',
       'medium_of_operation_Both', 'medium_of_operation_Desktop',
       'medium_of_operation_Smartphone', 'internet_option_Fiber_Optic',
       'internet_option_Mobile

In [ ]:
def f(s):
  if s=="Error":
    return mean_avg_frequency_login_days
  else:
    return s
mean_avg_frequency_login_days=0
c=0
for i in X.avg_frequency_login_days:
  if i!="Error":
    mean_avg_frequency_login_days+=float(i)
    c+=1
mean_avg_frequency_login_days/=c
X.avg_frequency_login_days=X.avg_frequency_login_days.apply(f)

In [ ]:
cols_for_Scaling=['days_since_last_login','age','avg_frequency_login_days','points_in_wallet','avg_time_spent','avg_transaction_value']
X[cols_for_Scaling]=scaler.fit_transform(X[cols_for_Scaling])
X.columns

Index(['age', 'days_since_last_login', 'avg_time_spent',
       'avg_transaction_value', 'avg_frequency_login_days', 'points_in_wallet',
       'gender_F', 'gender_M', 'gender_Unknown', 'region_category_City',
       'region_category_Town', 'region_category_Village',
       'membership_category_Basic Membership',
       'membership_category_Gold Membership',
       'membership_category_No Membership',
       'membership_category_Platinum Membership',
       'membership_category_Premium Membership',
       'membership_category_Silver Membership', 'joined_through_referral_?',
       'joined_through_referral_No', 'joined_through_referral_Yes',
       'preferred_offer_types_Credit/Debit Card Offers',
       'preferred_offer_types_Gift Vouchers/Coupons',
       'preferred_offer_types_Without Offers', 'medium_of_operation_?',
       'medium_of_operation_Both', 'medium_of_operation_Desktop',
       'medium_of_operation_Smartphone', 'internet_option_Fiber_Optic',
       'internet_option_Mobile

In [ ]:
X.shape

(28373, 51)

In [ ]:
Y.shape

(28373, 1)

In [ ]:
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y)
#type(X_train[0])""
X_train=np.array(X_train)
X_train.shape
Y_test[Y_test['churn_risk_score']==6]

churn_risk_score
13973                 6
35862                 6
3693                  6
7268                  6
27065                 6
...                 ...
3735                  6
11429                 6
19212                 6
34701                 6
8388                  6

[202 rows x 1 columns]

In [ ]:
Y_train=np.array(Y_train)

In [ ]:
print("x_train shape"+str(X_train.shape))
print("ytrain shape"+str(Y_train.shape))

x_train shape(21279, 51)
ytrain shape(21279, 1)


In [ ]:
#Y_train=np.reshape(Y_train,[])
df.iloc[6436]

customer_id                     fffe4300490044003700340036003500
Name                                                Brendon Eder
age                                                           11
gender                                                         M
security_no                                              AB2U35X
region_category                                          Village
membership_category                             Basic Membership
joining_date                                          2017-03-26
joined_through_referral                                      Yes
referral_id                                              CID7248
preferred_offer_types                      Gift Vouchers/Coupons
medium_of_operation                                      Desktop
internet_option                                            Wi-Fi
last_visit_time                                         18:35:07
days_since_last_login                                         12
avg_time_spent           

In [ ]:
X_train.shape
Y_train.shape

(5103, 6)

In [ ]:
model=tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(51,)),
    tf.keras.layers.Dense(256,activation='relu'),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dense(6,activation='softmax')]
)

In [ ]:
adam=tf.keras.optimizers.Adam(0.001)
model.compile(optimizer=adam,loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [ ]:
model.fit(X_train,Y_train,epochs=50)

Epoch 1/5
665/665 [==============================] - 1s 2ms/step - loss: 0.0556 - accuracy: 0.9836
Epoch 2/5
665/665 [==============================] - 1s 2ms/step - loss: 0.0693 - accuracy: 0.9772
Epoch 3/5
665/665 [==============================] - 1s 2ms/step - loss: 0.0678 - accuracy: 0.9766
Epoch 4/5
665/665 [==============================] - 1s 2ms/step - loss: 0.0441 - accuracy: 0.9877
Epoch 5/5
665/665 [==============================] - 1s 2ms/step - loss: 0.0533 - accuracy: 0.9833


In [ ]:
ahsdk=np.array(Y_test)
np.unique(ahsdk)

array([0, 1, 2, 3, 4, 5])

In [ ]:
ar=list(X_test.iloc[0])
ar=np.array(ar)
ar=np.reshape(ar,[51])
ar.shape

(51,)

In [ ]:
arr=model.predict(X_test)#6436 - 0
#np.argmax(model.predict(X_test)[0][0])
#X_test
#arr[0]
model.evaluate(X_test,Y_test)

222/222 [==============================] - 0s 2ms/step - loss: 1.7161 - accuracy: 0.7254


[1.7160574197769165, 0.725401759147644]

In [ ]:
s=[]
for i in arr:
  s.append(np.argmax(i))
s=np.array(s)
np.unique(s)

array([0, 1, 2, 3, 4, 5])

In [ ]:
li=X_test.index
d=dict()
count=0
for i in li:
  d[i]=s[count]
  count+=1
d

In [ ]:
#X_test.head()
df.iloc[6436]

customer_id                     fffe4300490044003700340036003500
Name                                                Brendon Eder
age                                                           11
gender                                                         M
security_no                                              AB2U35X
region_category                                          Village
membership_category                             Basic Membership
joining_date                                          2017-03-26
joined_through_referral                                      Yes
referral_id                                              CID7248
preferred_offer_types                      Gift Vouchers/Coupons
medium_of_operation                                      Desktop
internet_option                                            Wi-Fi
last_visit_time                                         18:35:07
days_since_last_login                                         12
avg_time_spent           

In [ ]:
model.evaluate(X_test,Y_test,verbose=2)

222/222 - 0s - loss: 1.7161 - accuracy: 0.7254


[1.7160574197769165, 0.725401759147644]

In [ ]:
from sklearn.naive_bayes import GaussianNB
m=GaussianNB()
m.fit(X_train,Y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
m.score(X_test,Y_test)

0.6532280800676629

In [ ]:
### process the test data set which is given
test=pd.read_csv('/content/test.csv')
test

customer_id  ...              feedback
0      fffe43004900440031003700300030003400  ...  Poor Product Quality
1      fffe43004900440031003900370037003300  ...          Poor Website
2      fffe43004900440034003800360037003000  ...   No reason specified
3      fffe43004900440036003200370033003400  ...          Too many ads
4      fffe43004900440035003000370031003900  ...          Poor Website
...                                     ...  ...                   ...
19914  fffe43004900440035003600330037003800  ...  Poor Product Quality
19915  fffe43004900440032003900370037003100  ...   No reason specified
19916  fffe43004900440036003100310036003700  ...   No reason specified
19917  fffe43004900440034003200330033003600  ...          Poor Website
19918  fffe43004900440036003200340030003100  ...          Too many ads

[19919 rows x 24 columns]

In [ ]:
test.region_category.unique()

array(['Village', 'Town', 'City', nan], dtype=object)

In [ ]:
scaleddf=test.drop(columns=['Name','customer_id','security_no','joining_date','referral_id','last_visit_time'],axis=1)
scaleddf

age gender  ...          complaint_status              feedback
0       50      F  ...            Not Applicable  Poor Product Quality
1       41      M  ...            Not Applicable          Poor Website
2       31      F  ...       Solved in Follow-up   No reason specified
3       64      M  ...  No Information Available          Too many ads
4       16      F  ...       Solved in Follow-up          Poor Website
...    ...    ...  ...                       ...                   ...
19914   12      M  ...            Not Applicable  Poor Product Quality
19915   40      F  ...            Not Applicable   No reason specified
19916   55      M  ...                  Unsolved   No reason specified
19917   17      F  ...            Not Applicable          Poor Website
19918   20      M  ...                  Unsolved          Too many ads

[19919 rows x 18 columns]

In [ ]:
ans=pd.DataFrame(test['customer_id'])
ans

customer_id
0      fffe43004900440031003700300030003400
1      fffe43004900440031003900370037003300
2      fffe43004900440034003800360037003000
3      fffe43004900440036003200370033003400
4      fffe43004900440035003000370031003900
...                                     ...
19914  fffe43004900440035003600330037003800
19915  fffe43004900440032003900370037003100
19916  fffe43004900440036003100310036003700
19917  fffe43004900440034003200330033003600
19918  fffe43004900440036003200340030003100

[19919 rows x 1 columns]

In [ ]:
ans['churn_risk_score']=np.nan
ans

customer_id  churn_risk_score
0      fffe43004900440031003700300030003400               NaN
1      fffe43004900440031003900370037003300               NaN
2      fffe43004900440034003800360037003000               NaN
3      fffe43004900440036003200370033003400               NaN
4      fffe43004900440035003000370031003900               NaN
...                                     ...               ...
19914  fffe43004900440035003600330037003800               NaN
19915  fffe43004900440032003900370037003100               NaN
19916  fffe43004900440036003100310036003700               NaN
19917  fffe43004900440034003200330033003600               NaN
19918  fffe43004900440036003200340030003100               NaN

[19919 rows x 2 columns]

In [ ]:
scaler=StandardScaler()
test=pd.get_dummies(scaleddf,columns=['gender','region_category','membership_category','joined_through_referral','preferred_offer_types','medium_of_operation','internet_option','used_special_discount','offer_application_preference','past_complaint','complaint_status','feedback'])
#X=pd.get_dummies(df['gender'])
def f(s):
  if s=="Error":
    return mean_avg_frequency_login_days
  else:
    return s
mean_avg_frequency_login_days=0
c=0
for i in X.avg_frequency_login_days:
  if i!="Error":
    mean_avg_frequency_login_days+=float(i)
    c+=1
mean_avg_frequency_login_days/=c
test.avg_frequency_login_days=test.avg_frequency_login_days.apply(f)
cols_for_Scaling=['days_since_last_login','age','avg_frequency_login_days','points_in_wallet','avg_time_spent','avg_transaction_value']
test[cols_for_Scaling]=scaler.fit_transform(test[cols_for_Scaling])
test.columns

Index(['age', 'days_since_last_login', 'avg_time_spent',
       'avg_transaction_value', 'avg_frequency_login_days', 'points_in_wallet',
       'gender_F', 'gender_M', 'gender_Unknown', 'region_category_City',
       'region_category_Town', 'region_category_Village',
       'membership_category_Basic Membership',
       'membership_category_Gold Membership',
       'membership_category_No Membership',
       'membership_category_Platinum Membership',
       'membership_category_Premium Membership',
       'membership_category_Silver Membership', 'joined_through_referral_?',
       'joined_through_referral_No', 'joined_through_referral_Yes',
       'preferred_offer_types_Credit/Debit Card Offers',
       'preferred_offer_types_Gift Vouchers/Coupons',
       'preferred_offer_types_Without Offers', 'medium_of_operation_?',
       'medium_of_operation_Both', 'medium_of_operation_Desktop',
       'medium_of_operation_Smartphone', 'internet_option_Fiber_Optic',
       'internet_option_Mobile

In [ ]:
test=np.array(test)
test[0]

array([ 0.82400209,  0.229394  ,  0.35188126,  0.58456712, -0.72779762,
        0.24908559,  1.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  1.        ,  0.        ,  0.        ,  1.        ,
        0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
        1.        ,  0.        ,  1.        ,  1.        ,  0.        ,
        1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ])

In [ ]:
ans_ar=model.predict(test)

In [ ]:
l=[]
for i in ans_ar:
  r=np.argmax(i)
  if r==0:
    l.append(-1)
  else:
    l.append(r)
l=np.array(l)
np.unique(l)

array([-1,  1,  2,  3,  4,  5])

In [ ]:
ans['churn_risk_score']=l
ans

customer_id  churn_risk_score
0      fffe43004900440031003700300030003400                 2
1      fffe43004900440031003900370037003300                 5
2      fffe43004900440034003800360037003000                 2
3      fffe43004900440036003200370033003400                 2
4      fffe43004900440035003000370031003900                 5
...                                     ...               ...
19914  fffe43004900440035003600330037003800                 2
19915  fffe43004900440032003900370037003100                 4
19916  fffe43004900440036003100310036003700                 4
19917  fffe43004900440034003200330033003600                 3
19918  fffe43004900440036003200340030003100                 5

[19919 rows x 2 columns]

In [ ]:
ans.to_csv('submit.csv')

In [ ]:
from sklearn.linear_model import LogisticRegression
rg=LogisticRegression()
rg.fit(X_train,Y_train)
rg.score(X_test,Y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.7074992951790245

In [ ]:
test=test.dropna()
np.any(np.isnan(test))

False

In [ ]:
yt=np.array(Y_test)
np.unique(yt)
l=rg.predict(test)
l

array([2, 2, 2, ..., 4, 3, 2])

In [ ]:
l=np.array(l)
np.median(l)

3.0

In [ ]:
test

age  ...  feedback_User Friendly Website
0      0.824002  ...                               0
1      0.258566  ...                               0
2     -0.369697  ...                               0
3      1.703570  ...                               0
4     -1.312091  ...                               0
...         ...  ...                             ...
19914 -1.563396  ...                               0
19915  0.195739  ...                               0
19916  1.138133  ...                               0
19917 -1.249265  ...                               0
19918 -1.060786  ...                               0

[17956 rows x 51 columns]

In [ ]:
ans['churn_risk_score']=3

In [ ]:
ans

customer_id  churn_risk_score
0      fffe43004900440031003700300030003400                 3
1      fffe43004900440031003900370037003300                 3
2      fffe43004900440034003800360037003000                 3
3      fffe43004900440036003200370033003400                 3
4      fffe43004900440035003000370031003900                 3
...                                     ...               ...
19914  fffe43004900440035003600330037003800                 3
19915  fffe43004900440032003900370037003100                 3
19916  fffe43004900440036003100310036003700                 3
19917  fffe43004900440034003200330033003600                 3
19918  fffe43004900440036003200340030003100                 3

[19919 rows x 2 columns]

In [ ]:
k=0
for i in test.index:
  ans.at[i,'churn_risk_score']=l[k]
  k+=1

In [ ]:
ans

customer_id  churn_risk_score
0      fffe43004900440031003700300030003400                 2
1      fffe43004900440031003900370037003300                 2
2      fffe43004900440034003800360037003000                 2
3      fffe43004900440036003200370033003400                 3
4      fffe43004900440035003000370031003900                 4
...                                     ...               ...
19914  fffe43004900440035003600330037003800                 2
19915  fffe43004900440032003900370037003100                 4
19916  fffe43004900440036003100310036003700                 4
19917  fffe43004900440034003200330033003600                 3
19918  fffe43004900440036003200340030003100                 2

[19919 rows x 2 columns]

In [ ]:
ls=ans['churn_risk_score']
l=np.array(l)
np.unique(l)

array([0, 1, 2, 3, 4])

In [ ]:
ans[ans['churn_risk_score']==-1]

Empty DataFrame
Columns: [customer_id, churn_risk_score]
Index: []